name: "Deploy Application/Service"
description: "Deploy Sample Book App service via pm2"
inputs:
  environment:
    description: "Environment where to deploy Sample Book App"
    required: true
  port:
    required: true
runs:
  using: composite
  steps:
    - run: echo "Deployment to ${{ inputs.environment }} environment has started.."
      shell: powershell
    - name: Install all dependencies
      run: npm install
      shell: powershell
    - name: Cleanup of old runnig service
      shell: powershell
      run: .\node_modules\.bin\pm2 delete "books-${{ inputs.environment }}"
      continue-on-error: true
    - name: Running service
      run: .\node_modules\.bin\pm2 start .\index.js --name "books-${{ inputs.environment }}" -- -- "${{ inputs.port }}"
      shell: powershell
    - run: echo "Deployment to ${{ inputs.environment }} environment finished.."
      shell: powershell
