name: Sample Book App Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."
      - name: Install all dependencies
        run: npm install
      - name: Print step name
        run: echo "All dependencies have been installed successfully.."
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo "Deployment to DEV environment has started.."
      - name: Install all dependencies
        run: npm install
      - name: Cleanup of old runnig service
        shell: bash
        run: ./node_modules/.bin/pm2 delete "books-DEV" || exit 0
      - name: Running service
        run: ./node_modules/.bin/pm2 start index.js --name "books-DEV" -- 1010
      - run: echo "Deployment to DEV environment finished.."
  test-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing Sample Book Application service has started on DEV environment.."

  deploy-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo "Deployment to STG environment has started.."
      - name: Install all dependencies
        run: npm install
      - name: Cleanup of old runnig service
        shell: bash
        run: ./node_modules/.bin/pm2 delete "books-STG" || exit 0
      - name: Running service
        run: ./node_modules/.bin/pm2 start index.js --name "books-STG" -- 1010
      - run: echo "Deployment to STG environment finished.."
  test-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing Sample Book Application service has started on STG environment.."

  deploy-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo "Deployment to PRD environment has started.."
      - name: Install all dependencies
        run: npm install
      - name: Cleanup of old runnig service
        shell: bash
        run: ./node_modules/.bin/pm2 delete "books-PRD" || exit 0
      - name: Running service
        run: ./node_modules/.bin/pm2 start index.js --name "books-PRD" -- 1010
      - run: echo "Deployment to PRD environment finished.."
  test-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing Sample Book Application service has started on PRD environment.."
