name: Sample Book App Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."
      - name: Install all dependencies
        run: npm install
      - name: Print step name
        run: echo "All dependencies have been installed successfully.."
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo "Deployment to DEV environment has started.."
      - name: Cleanup of old runnig service
        run: .\\node_modules\\.bin\\pm2 delete \"books-dev\" || exit 0
      - name: Running service
        run: .\\node_modules\\.bin\\pm2 start -n \"books-dev\" index.js -- -- 1010
      - run: echo "Deployment to DEV environment finished.."

    # echo "Deployment to ${environment} environment has started.."
    # git branch: 'main', poll: true, url: 'https://github.com/DimitrijevsArtjoms/sample-book-app-2026.git'
    # powershell 'npm install'
    # powershell 'ls'
    # bat ".\\node_modules\\.bin\\pm2 delete \"books-${environment}\" || exit 0"
    # powershell ".\\node_modules\\.bin\\pm2 start -n \"books-${environment}\" index.js -- -- ${port}"

    # echo "Deployment to ${environment} environment finished.."
  test-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing Sample Book Application service has started on DEV environment.."
  deploy-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to STG environment has started.."
  test-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing Sample Book Application service has started on STG environment.."
  deploy-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to PRD environment has started.."
  test-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing Sample Book Application service has started on PRD environment.."
